### ISSUE TITLE
Plugin fails to install on IC-203

### ISSUE THREAD

**Issue by brandisimus** [jansorg/tezos-intellij#106]
IntilliJ fails to find it in the repository, and if downloaded and installed manually it produces the following message:

`Plugin 'Tezos' (version '1.0.1') is not compatible with the current version of the IDE, because it requires build 193.* or older but the current build is IC-203.5981.155`

**Comment by jansorg** [comment]
I've uploaded version 1.0.2 for 2020.3+, it should be approved in the next 48 hours.
https://plugins.jetbrains.com/plugin/11125-tezos/versions/stable/110831
